# Generated by Django 6.0.5 on 2026-07-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="familymember",
            name="role",
        ),
        migrations.AddField(
            model_name="familymember",
            name="permissions",
            field=models.JSONField(default=dict),
        ),
    ]
