# Generated by Django 6.0.5 on 2026-07-30 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_familymember_role_familymember_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="carerecord",
            name="pregnancycase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.pregnancycase",
            ),
        ),
    ]
