# Generated by Django 5.2 on 2026-08-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_carerecord_pregnancycase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="babyinformation",
            name="production_method",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
