# Generated by Django 5.2 on 2026-08-13 16:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_fix_production_method_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="JoinRequest",
            fields=[
                ("joinrequest_id", models.AutoField(primary_key=True, serialize=False)),
                ("join_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "pregnancycase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.pregnancycase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "joinrequest",
                "managed": True,
                "unique_together": {("pregnancycase", "user")},
            },
        ),
    ]
